from __future__ import annotations

import json
import logging
import textwrap
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from hermeshq.config import get_settings
from hermeshq.core.security import create_agent_service_token
from hermeshq.models.agent import Agent
from hermeshq.models.permission_policy import PermissionPolicy
from hermeshq.services.credentials import require_secret_value
from hermeshq.services.env_sanitize import build_safe_env
from hermeshq.services.secret_vault import SecretVault

logger = logging.getLogger(__name__)


class PiInstallationManager:
    """Manages Pi agent workspaces, settings, and extensions."""

    def __init__(
        self,
        secret_vault: SecretVault,
        workspace_manager,
        session_factory: async_sessionmaker[AsyncSession] | None = None,
    ) -> None:
        self.secret_vault = secret_vault
        self.workspace_manager = workspace_manager
        self.session_factory = session_factory

    async def sync_agent_installation(self, agent: Agent) -> None:
        workspace = self.workspace_manager.build_workspace_path(agent.id)
        pi_home = workspace / ".pi"

        pi_home.mkdir(parents=True, exist_ok=True)
        (pi_home / "extensions").mkdir(exist_ok=True)
        (pi_home / "skills").mkdir(exist_ok=True)
        (pi_home / "sessions").mkdir(exist_ok=True)

        policy = await self._load_policy(agent)
        api_key = await self._resolve_api_key(agent)
        self._write_settings(agent, pi_home)
        self._write_models(agent, pi_home)
        self._write_security_extension(agent, pi_home, policy)
        self._write_integration_extension(agent, pi_home)

    async def _load_policy(self, agent: Agent) -> PermissionPolicy | None:
        if not agent.permission_policy_id or not self.session_factory:
            return None
        async with self.session_factory() as session:
            return await session.get(PermissionPolicy, agent.permission_policy_id)

    async def _resolve_api_key(self, agent: Agent) -> str | None:
        if not agent.api_key_ref or not self.session_factory:
            return None
        async with self.session_factory() as session:
            return await require_secret_value(session, self.secret_vault, agent.api_key_ref)

    def _write_settings(self, agent: Agent, pi_home: Path) -> None:
        config = agent.pi_config or {}
        settings = {
            "compaction": config.get("compaction", {"enabled": True, "threshold_tokens": 100000}),
            "defaultProjectTrust": config.get("project_trust", "always"),
            "retry": {"enabled": True, "maxRetries": 3},
        }
        (pi_home / "settings.json").write_text(json.dumps(settings, indent=2))

    def _write_models(self, agent: Agent, pi_home: Path) -> None:
        model_id = agent.model or "gpt-4o"
        base_url = agent.base_url or "https://api.openai.com/v1"
        provider_name = "nvidia" if "nvidia" in (agent.provider or "") else "openai"
        api_key_env = "NVIDIA_API_KEY" if provider_name == "nvidia" else "OPENAI_API_KEY"

        models = {
            "providers": {
                provider_name: {
                    "baseUrl": base_url,
                    "api": "openai-completions",
                    "apiKey": "$" + api_key_env,
                    "models": [{
                        "id": model_id,
                        "name": model_id.split("/")[-1],
                        "reasoning": False,
                        "input": ["text"],
                        "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
                        "contextWindow": 128000,
                        "maxTokens": 4096,
                    }],
                }
            }
        }
        (pi_home / "models.json").write_text(json.dumps(models, indent=2))

    def _write_security_extension(
        self, agent: Agent, pi_home: Path, policy: PermissionPolicy | None,
    ) -> None:
        tool_rules = (policy.tool_rules if policy else {}) or {}
        command_rules = (policy.command_rules if policy else {}) or {}
        path_rules = (policy.path_rules if policy else {}) or {}
        approval_rules = (policy.approval_rules if policy else {}) or {}
        network_rules = (policy.network_rules if policy else {}) or {}

        allowed_tools = json.dumps(tool_rules.get("allow", ["*"]))
        denied_commands = json.dumps(command_rules.get("deny", []))
        protected_paths = json.dumps(path_rules.get("deny_paths", []))
        require_approval = json.dumps(approval_rules.get("require_approval_for", []))
        deny_all_net = json.dumps(network_rules.get("deny_all", False))
        allowed_domains = json.dumps(network_rules.get("allow_domains", []))

        extension = textwrap.dedent(f"""\
            // GENERATED BY HERMESHQ — DO NOT EDIT
            import type {{ ExtensionAPI }} from "@earendil-works/pi-coding-agent";

            const API_URL = process.env.HERMESHQ_INTERNAL_API_URL ?? "";
            const AGENT_TOKEN = process.env.HERMESHQ_AGENT_TOKEN ?? "";
            const AGENT_ID = process.env.HERMESHQ_AGENT_ID ?? "";

            const ALLOWED_TOOLS = {allowed_tools};
            const DENIED_COMMANDS = {denied_commands};
            const PROTECTED_PATHS = {protected_paths};
            const REQUIRE_APPROVAL = {require_approval};
            const DENY_ALL_NET = {deny_all_net};
            const ALLOWED_DOMAINS = {allowed_domains};

            export default function (pi: ExtensionAPI) {{
              pi.on("tool_call", async (event, _ctx) => {{
                // --- Tool allowlist ---
                if (!ALLOWED_TOOLS.includes("*") && !ALLOWED_TOOLS.includes(event.toolName)) {{
                  return {{ block: true, reason: `Tool '${{event.toolName}}' not in allowlist` }};
                }}

                // --- Bash command rules ---
                if (event.toolName === "bash") {{
                  const cmd = (event.input as {{ command?: string }}).command ?? "";
                  for (const pattern of DENIED_COMMANDS) {{
                    if (globMatch(cmd, pattern)) {{
                      return {{ block: true, reason: `Command denied: matches '${{pattern}}'` }};
                    }}
                  }}
                  for (const pattern of REQUIRE_APPROVAL) {{
                    if (globMatch(cmd, pattern) || globMatch(`bash:${{cmd}}`, pattern)) {{
                      const approved = await requestApproval(cmd);
                      if (!approved) return {{ block: true, reason: "Approval denied" }};
                    }}
                  }}
                  // Network restrictions: check if command makes outbound requests
                  if (DENY_ALL_NET && /curl|wget|nc |ssh|scp|ftp/.test(cmd)) {{
                    const domainMatch = cmd.match(/https?:\\/\\/([^/\\s]+)/);
                    if (domainMatch) {{
                      const domain = domainMatch[1];
                      if (!ALLOWED_DOMAINS.some((p: string) => globMatch(domain, p))) {{
                        return {{ block: true, reason: `Network access denied to ${{domain}}` }};
                      }}
                    }} else {{
                      return {{ block: true, reason: "Network access denied by policy" }};
                    }}
                  }}
                }}

                // --- File path protection ---
                if (["read", "write", "edit"].includes(event.toolName)) {{
                  const path = (event.input as {{ path?: string }}).path ?? "";
                  for (const pattern of PROTECTED_PATHS) {{
                    if (globMatch(path, pattern)) {{
                      return {{ block: true, reason: `Path protected: matches '${{pattern}}'` }};
                    }}
                  }}
                }}
              }});
            }}

            async function requestApproval(command: string): Promise<boolean> {{
              if (!API_URL || !AGENT_TOKEN) return false;
              try {{
                const res = await fetch(`${{API_URL}}/control/approval`, {{
                  method: "POST",
                  headers: {{
                    "Content-Type": "application/json",
                    "X-HermesHQ-Agent-ID": AGENT_ID,
                    "X-HermesHQ-Agent-Token": AGENT_TOKEN,
                  }},
                  body: JSON.stringify({{ command }}),
                }});
                const data = await res.json();
                return data.approved === true;
              }} catch {{
                return false;
              }}
            }}

            function globMatch(text: string, pattern: string): boolean {{
              const re = new RegExp(
                "^" + pattern
                  .replace(/[.+^${{}}()|[\\]\\\\]/g, "\\\\$&")
                  .replace(/\\*\\*/g, ".*")
                  .replace(/\\*/g, "[^/]*")
                  .replace(/\\?/g, ".") + "$"
              );
              return re.test(text);
            }}
            """)
        (pi_home / "extensions" / "hermeshq-security.ts").write_text(extension)

    def _write_integration_extension(self, agent: Agent, pi_home: Path) -> None:
        integrations = agent.integration_configs or {}
        integrations_json = json.dumps({k: True for k in integrations.keys()})
        agent_id = agent.id

        extension = textwrap.dedent(f"""\
            // GENERATED BY HERMESHQ — Exposes platform integrations as Pi tools
            import type {{ ExtensionAPI }} from "@earendil-works/pi-coding-agent";
            import {{ Type }} from "typebox";

            const API_URL = process.env.HERMESHQ_INTERNAL_API_URL ?? "";
            const AGENT_TOKEN = process.env.HERMESHQ_AGENT_TOKEN ?? "";
            const AGENT_ID = "{agent_id}";

            async function callIntegration(integrationSlug: string, action: string, args: Record<string, unknown>) {{
              const res = await fetch(
                `${{API_URL}}/internal/control/agents/${{AGENT_ID}}/integrations/${{integrationSlug}}/actions/${{action}}`,
                {{
                  method: "POST",
                  headers: {{
                    "Content-Type": "application/json",
                    "X-HermesHQ-Agent-ID": AGENT_ID,
                    "X-HermesHQ-Agent-Token": AGENT_TOKEN,
                  }},
                  body: JSON.stringify(args),
                }},
              );
              return res.json();
            }}

            const INTEGRATIONS = {integrations_json};

            export default function (pi: ExtensionAPI) {{
              for (const slug of Object.keys(INTEGRATIONS)) {{
                const toolName = `integration_${{slug}}`.replace(/-/g, "_");
                pi.registerTool({{
                  name: toolName,
                  label: slug,
                  description: `Call ${{slug}} integration action`,
                  parameters: Type.Object({{
                    action: Type.String({{ description: "Action name (e.g. send_mail, list_events)" }}),
                    args: Type.Record(Type.String(), Type.Any(), {{ description: "Action arguments", default: {{}} }}),
                  }}),
                  async execute(_id, params) {{
                    const result = await callIntegration(slug, params.action, params.args ?? {{}});
                    const text = typeof result === "string" ? result : JSON.stringify(result, null, 2);
                    return {{ content: [{{ type: "text", text }}], details: {{}} }};
                  }},
                }});
              }}
            }}
            """)
        (pi_home / "extensions" / "hermeshq-integrations.ts").write_text(extension)

    async def build_process_env(self, agent: Agent) -> dict[str, str]:
        env = build_safe_env()
        env["HERMESHQ_AGENT_ID"] = agent.id
        env["HERMESHQ_AGENT_TOKEN"] = create_agent_service_token(agent.id)
        settings = get_settings()
        env["HERMESHQ_INTERNAL_API_URL"] = settings.internal_api_base_url.rstrip("/")

        if agent.api_key_ref and self.session_factory:
            async with self.session_factory() as session:
                api_key = await require_secret_value(session, self.secret_vault, agent.api_key_ref)
        else:
            api_key = None

        if api_key:
            provider = agent.provider or "openai"
            if provider.startswith("anthropic"):
                env["ANTHROPIC_API_KEY"] = api_key
            elif "nvidia" in provider:
                env["NVIDIA_API_KEY"] = api_key
                env["OPENAI_API_KEY"] = api_key
            else:
                env["OPENAI_API_KEY"] = api_key
                if agent.base_url:
                    env["OPENAI_BASE_URL"] = agent.base_url

        if agent.model:
            env["PI_MODEL"] = agent.model
            self._write_default_models_json(agent)

        return env

    def _write_default_models_json(self, agent: Agent) -> None:
        """Write models.json to ~/.pi/agent/ so ModelRuntime.create() picks it up."""
        import os
        home = os.path.expanduser("~")
        pi_agent_dir = os.path.join(home, ".pi", "agent")
        os.makedirs(pi_agent_dir, exist_ok=True)
        models_path = os.path.join(pi_agent_dir, "models.json")

        model_id = agent.model or "gpt-4o"
        # Use short ID for Pi SDK (openai provider expects short), NIM accepts short via openai baseUrl
        short_id = model_id.split("/")[-1] if "/" in model_id else model_id
        base_url = agent.base_url or "https://api.openai.com/v1"

        models = {
            "providers": {
                "openai": {
                    "baseUrl": base_url,
                    "api": "openai-completions",
                    "apiKey": "$OPENAI_API_KEY",
                    "models": [{
                        "id": short_id,
                        "name": short_id,
                        "reasoning": False,
                        "input": ["text"],
                        "cost": {"input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0},
                        "contextWindow": 128000,
                        "maxTokens": 4096,
                    }],
                }
            }
        }
        with open(models_path, "w") as f:
            json.dump(models, f, indent=2)

    def compose_system_prompt(self, agent: Agent) -> str:
        parts = []
        if agent.system_prompt:
            parts.append(agent.system_prompt)
        parts.append(
            f"\nYou are running inside HermesHQ as agent '{agent.friendly_name or agent.name}' "
            f"(ID: {agent.id}). Use the provided tools to complete tasks."
        )
        return "\n".join(parts)
