from __future__ import annotations

import json
import logging
import textwrap
from pathlib import Path

from hermeshq.config import get_settings
from hermeshq.core.security import create_agent_service_token
from hermeshq.models.agent import Agent
from hermeshq.services.credentials import require_secret_value
from hermeshq.services.env_sanitize import build_safe_env
from hermeshq.services.secret_vault import SecretVault

logger = logging.getLogger(__name__)


class PiInstallationManager:
    """Manages Pi agent workspaces, settings, and extensions."""

    def __init__(self, secret_vault: SecretVault, workspace_manager) -> None:
        self.secret_vault = secret_vault
        self.workspace_manager = workspace_manager

    async def sync_agent_installation(self, agent: Agent) -> None:
        workspace = self.workspace_manager.build_workspace_path(agent.id)
        pi_home = workspace / ".pi"

        pi_home.mkdir(parents=True, exist_ok=True)
        (pi_home / "extensions").mkdir(exist_ok=True)
        (pi_home / "skills").mkdir(exist_ok=True)
        (pi_home / "sessions").mkdir(exist_ok=True)

        self._write_settings(agent, pi_home)
        self._write_security_extension(agent, pi_home)
        self._write_integration_extension(agent, pi_home)

    def _write_settings(self, agent: Agent, pi_home: Path) -> None:
        config = agent.pi_config or {}
        settings = {
            "compaction": config.get("compaction", {"enabled": True, "threshold_tokens": 100000}),
            "defaultProjectTrust": config.get("project_trust", "always"),
            "retry": {"enabled": True, "maxRetries": 3},
        }
        (pi_home / "settings.json").write_text(json.dumps(settings, indent=2))

    def _write_security_extension(self, agent: Agent, pi_home: Path) -> None:
        policy = agent.permission_policy
        tool_rules = (policy.tool_rules if policy else {}) or {}
        command_rules = (policy.command_rules if policy else {}) or {}
        path_rules = (policy.path_rules if policy else {}) or {}
        approval_rules = (policy.approval_rules if policy else {}) or {}

        allowed_tools = json.dumps(tool_rules.get("allow", ["*"]))
        denied_commands = json.dumps(command_rules.get("deny", []))
        protected_paths = json.dumps(path_rules.get("deny_paths", []))
        require_approval = json.dumps(approval_rules.get("require_approval_for", []))

        extension = textwrap.dedent(f"""\
            // GENERATED BY HERMESHQ — DO NOT EDIT
            import type {{ ExtensionAPI }} from "@earendil-works/pi-coding-agent";

            export default function (pi: ExtensionAPI) {{
              const ALLOWED_TOOLS = {allowed_tools};
              const DENIED_COMMANDS = {denied_commands};
              const PROTECTED_PATHS = {protected_paths};
              const REQUIRE_APPROVAL = {require_approval};

              pi.on("tool_call", async (event, ctx) => {{
                if (!ALLOWED_TOOLS.includes("*") && !ALLOWED_TOOLS.includes(event.toolName)) {{
                  return {{ block: true, reason: `Tool '${{event.toolName}}' not in allowlist` }};
                }}
                if (event.toolName === "bash") {{
                  const cmd = (event.input as {{ command?: string }}).command ?? "";
                  for (const pattern of DENIED_COMMANDS) {{
                    if (globMatch(cmd, pattern)) {{
                      return {{ block: true, reason: `Command denied by policy: ${{pattern}}` }};
                    }}
                  }}
                  for (const pattern of REQUIRE_APPROVAL) {{
                    if (globMatch(cmd, pattern) || globMatch(`bash:${{cmd}}`, pattern)) {{
                      const ok = await ctx.ui.confirm("Approval required", `Allow: ${{cmd}}?`);
                      if (!ok) return {{ block: true, reason: "Approval denied by user" }};
                    }}
                  }}
                }}
                if (["read", "write", "edit"].includes(event.toolName)) {{
                  const path = (event.input as {{ path?: string }}).path ?? "";
                  for (const pattern of PROTECTED_PATHS) {{
                    if (globMatch(path, pattern)) {{
                      return {{ block: true, reason: `Path protected by policy: ${{pattern}}` }};
                    }}
                  }}
                }}
              }});
            }}

            function globMatch(text: string, pattern: string): boolean {{
              const re = new RegExp(
                "^" + pattern
                  .replace(/[.+^${{}}()|[\\]\\\\]/g, "\\\\$&")
                  .replace(/\\*\\*/g, ".*")
                  .replace(/\\*/g, "[^/]*")
                  .replace(/\\?/g, ".") + "$"
              );
              return re.test(text);
            }}
            """)
        (pi_home / "extensions" / "hermeshq-security.ts").write_text(extension)

    def _write_integration_extension(self, agent: Agent, pi_home: Path) -> None:
        integrations = agent.integration_configs or {}
        integrations_json = json.dumps({k: True for k in integrations.keys()})

        extension = textwrap.dedent(f"""\
            // GENERATED BY HERMESHQ — Exposes platform integrations as Pi tools
            import type {{ ExtensionAPI }} from "@earendil-works/pi-coding-agent";
            import {{ Type }} from "typebox";

            const API_URL = process.env.HERMESHQ_INTERNAL_API_URL!;
            const AGENT_TOKEN = process.env.HERMESHQ_AGENT_TOKEN!;
            const AGENT_ID = process.env.HERMESHQ_AGENT_ID!;
            const INTEGRATIONS = {integrations_json};

            async function callControl(path: string, method: string, body?: any) {{
              const res = await fetch(`${{API_URL}}${{path}}`, {{
                method,
                headers: {{
                  "Content-Type": "application/json",
                  "X-HermesHQ-Agent-ID": AGENT_ID,
                  "X-HermesHQ-Agent-Token": AGENT_TOKEN,
                }},
                body: body ? JSON.stringify(body) : undefined,
              }});
              return res.json();
            }}

            export default function (pi: ExtensionAPI) {{
              for (const slug of Object.keys(INTEGRATIONS)) {{
                pi.registerTool({{
                  name: `integration_${{slug}}`.replace(/-/g, "_"),
                  label: slug,
                  description: `Call ${{slug}} integration`,
                  parameters: Type.Object({{
                    action: Type.String({{ description: "Action name" }}),
                    args: Type.Record(Type.String(), Type.Any(), {{ description: "Action arguments" }}),
                  }}),
                  async execute(_id, params) {{
                    const result = await callControl(
                      `/control/integrations/${{slug}}/actions/${{params.action}}`,
                      "POST",
                      params.args
                    );
                    return {{ content: [{{ type: "text", text: JSON.stringify(result, null, 2) }}], details: {{}} }};
                  }},
                }});
              }}
            }}
            """)
        (pi_home / "extensions" / "hermeshq-integrations.ts").write_text(extension)

    def build_process_env(self, agent: Agent) -> dict[str, str]:
        env = build_safe_env()
        env["HERMESHQ_AGENT_ID"] = agent.id
        env["HERMESHQ_AGENT_TOKEN"] = create_agent_service_token(agent.id)
        settings = get_settings()
        env["HERMESHQ_INTERNAL_API_URL"] = settings.internal_api_base_url.rstrip("/")

        api_key = None
        if agent.api_key_ref:
            api_key = require_secret_value(self.secret_vault, agent.api_key_ref)

        if api_key:
            provider = agent.provider or "openai"
            if provider.startswith("anthropic"):
                env["ANTHROPIC_API_KEY"] = api_key
            elif provider.startswith("openai"):
                env["OPENAI_API_KEY"] = api_key
            else:
                env["OPENAI_API_KEY"] = api_key
                if agent.base_url:
                    env["OPENAI_BASE_URL"] = agent.base_url

        if agent.model:
            env["PI_MODEL"] = agent.model

        return env

    def compose_system_prompt(self, agent: Agent) -> str:
        parts = []
        if agent.system_prompt:
            parts.append(agent.system_prompt)
        parts.append(
            f"\nYou are running inside HermesHQ as agent '{agent.friendly_name or agent.name}' "
            f"(ID: {agent.id}). Use the provided tools to complete tasks."
        )
        return "\n".join(parts)
