from hermeshq.models.provider import ProviderDefinition


BUILTIN_PROVIDERS: list[dict] = [
    {
        "slug": "kimi-coding",
        "name": "Kimi Coding",
        "runtime_provider": "kimi-coding",
        "auth_type": "api_key",
        "base_url": "https://api.kimi.com/coding/v1",
        "default_model": "kimi-k2.5",
        "description": "Moonshot Kimi coding provider using the Kimi coding API endpoint.",
        "docs_url": "https://platform.moonshot.ai/",
        "secret_placeholder": "KIMI API key",
        "supports_secret_ref": True,
        "supports_custom_base_url": True,
        "enabled": True,
        "sort_order": 10,
    },
    {
        "slug": "zai",
        "name": "Z.AI Coding Plan",
        "runtime_provider": "zai",
        "auth_type": "api_key",
        "base_url": "https://api.z.ai/api/coding/paas/v4",
        "default_model": "glm-5-turbo",
        "description": "Z.AI coding plan endpoint for GLM coding models.",
        "docs_url": "https://docs.z.ai/devpack/faq",
        "secret_placeholder": "Z.AI API key",
        "supports_secret_ref": True,
        "supports_custom_base_url": True,
        "enabled": True,
        "sort_order": 20,
    },
    {
        "slug": "huggingface",
        "name": "Hugging Face Router",
        "runtime_provider": "huggingface",
        "auth_type": "api_key",
        "base_url": "https://router.huggingface.co/v1",
        "default_model": "Qwen/Qwen3.5-35B-A3B",
        "description": "Direct Hugging Face Router endpoint for OpenAI-compatible chat models.",
        "docs_url": "https://huggingface.co/docs/inference-providers/index",
        "secret_placeholder": "Hugging Face token",
        "supports_secret_ref": True,
        "supports_custom_base_url": True,
        "enabled": True,
        "sort_order": 25,
    },
    {
        "slug": "openrouter",
        "name": "OpenRouter API",
        "runtime_provider": "openrouter",
        "auth_type": "api_key",
        "base_url": "https://openrouter.ai/api/v1",
        "default_model": "anthropic/claude-sonnet-4",
        "description": "OpenRouter unified API for multi-provider model access.",
        "docs_url": "https://openrouter.ai/docs/quickstart",
        "secret_placeholder": "OpenRouter API key",
        "supports_secret_ref": True,
        "supports_custom_base_url": True,
        "enabled": True,
        "sort_order": 30,
    },
    {
        "slug": "openai-api",
        "name": "OpenAI API",
        "runtime_provider": "openai",
        "auth_type": "api_key",
        "base_url": "https://api.openai.com/v1",
        "default_model": "gpt-4.1",
        "description": "Direct OpenAI API using API keys.",
        "docs_url": "https://platform.openai.com/docs/overview",
        "secret_placeholder": "OpenAI API key",
        "supports_secret_ref": True,
        "supports_custom_base_url": True,
        "enabled": True,
        "sort_order": 40,
    },
    {
        "slug": "gemini-api",
        "name": "Gemini API",
        "runtime_provider": "openai",
        "auth_type": "api_key",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai/",
        "default_model": "gemini-2.5-pro",
        "description": "Gemini via Google's OpenAI-compatible endpoint.",
        "docs_url": "https://ai.google.dev/gemini-api/docs/openai",
        "secret_placeholder": "Gemini API key",
        "supports_secret_ref": True,
        "supports_custom_base_url": True,
        "enabled": True,
        "sort_order": 50,
    },
    {
        "slug": "anthropic-api",
        "name": "Anthropic API",
        "runtime_provider": "anthropic",
        "auth_type": "api_key",
        "base_url": "https://api.anthropic.com",
        "default_model": "claude-sonnet-4-5",
        "description": "Direct Anthropic API.",
        "docs_url": "https://docs.anthropic.com/en/api/getting-started",
        "secret_placeholder": "Anthropic API key",
        "supports_secret_ref": True,
        "supports_custom_base_url": False,
        "enabled": True,
        "sort_order": 60,
    },
    {
        "slug": "minimax-api",
        "name": "MiniMax API",
        "runtime_provider": "minimax",
        "auth_type": "api_key",
        "base_url": "https://api.minimax.io/anthropic",
        "default_model": "MiniMax-M2.7",
        "description": "MiniMax Anthropic-compatible endpoint.",
        "docs_url": "https://www.minimax.io/platform/document/ChatCompletion_v2?key=66701c8be1b39c7fc7f4ea81",
        "secret_placeholder": "MiniMax API key",
        "supports_secret_ref": True,
        "supports_custom_base_url": True,
        "enabled": True,
        "sort_order": 65,
    },
    {
        "slug": "deepseek-api",
        "name": "DeepSeek API",
        "runtime_provider": "deepseek",
        "auth_type": "api_key",
        "base_url": "https://api.deepseek.com/v1",
        "default_model": "deepseek-chat",
        "description": "Direct DeepSeek API.",
        "docs_url": "https://api-docs.deepseek.com/",
        "secret_placeholder": "DeepSeek API key",
        "supports_secret_ref": True,
        "supports_custom_base_url": True,
        "enabled": True,
        "sort_order": 70,
    },
    {
        "slug": "xai-api",
        "name": "xAI API",
        "runtime_provider": "xai",
        "auth_type": "api_key",
        "base_url": "https://api.x.ai/v1",
        "default_model": "grok-4-1-fast-reasoning",
        "description": "Direct xAI API.",
        "docs_url": "https://docs.x.ai/docs/overview",
        "secret_placeholder": "xAI API key",
        "supports_secret_ref": True,
        "supports_custom_base_url": True,
        "enabled": True,
        "sort_order": 75,
    },
    {
        "slug": "alibaba-api",
        "name": "Alibaba DashScope",
        "runtime_provider": "alibaba",
        "auth_type": "api_key",
        "base_url": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
        "default_model": "qwen3.5-plus",
        "description": "Alibaba Cloud DashScope OpenAI-compatible endpoint.",
        "docs_url": "https://www.alibabacloud.com/help/en/model-studio/developer-reference/compatibility-of-openai-with-dashscope",
        "secret_placeholder": "DashScope API key",
        "supports_secret_ref": True,
        "supports_custom_base_url": True,
        "enabled": True,
        "sort_order": 80,
    },
]


def seed_provider_defaults(existing: ProviderDefinition | None, payload: dict) -> None:
    if not existing:
        return
    existing.name = existing.name or payload["name"]
    existing.runtime_provider = existing.runtime_provider or payload["runtime_provider"]
    existing.auth_type = existing.auth_type or payload["auth_type"]
    existing.base_url = existing.base_url or payload["base_url"]
    existing.default_model = existing.default_model or payload["default_model"]
    existing.description = existing.description or payload["description"]
    existing.docs_url = existing.docs_url or payload["docs_url"]
    existing.secret_placeholder = existing.secret_placeholder or payload["secret_placeholder"]
